version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    depends_on:
      - "redis"
    volumes:
      - .:/opt/hackcoinbot
    env_file:
      - access.env
    entrypoint: ./wait-for-it.sh -t 15 redis:6379 -- python app.py

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - "6379:6379"
